apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: unreal-server-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: unreal-server
  updatePolicy:
    updateMode: "Auto"
