apiVersion: v1
kind: Service
metadata:
  name: unreal-nodeport
spec:
  type: NodePort
  selector:
    app: unreal-server
  ports:
    # - name: unreal-port
    - port: 7777
      protocol: UDP
      targetPort: 7777
      nodePort: 30000
