apiVersion: v1
kind: Service
metadata:
  name: unreal-service
spec:
  type: LoadBalancer
  selector:
    app: unreal-server
  ports:
    - protocol: UDP
      port: 7777
      targetPort: 7777
    # - name: "tcp"
    #   protocol: TCP
    #   port: 7777
    #   targetPort: 7777
  # externalIPs:
  #   - 192.168.2.64
